/**
 * Freecat-Blog 构建编排器
 *
 * 整体流程：
 *   1. 清理 dist 并搬运 assets / image
 *   2. 加载站点 / 社交 / 关于页面三份配置（Control/*.md）
 *   3. 准备模板引擎（注入 partials + tailwind config + SITE_*）
 *   4. 依次生成：post 详情页 → 分页首页 → all.html → search.html + 索引 → about.html → sitemap/robots
 *
 * 各步骤的实际逻辑都拆在 build/*.js 中，本文件仅做编排。
 */

const fs = require('fs');
const path = require('path');
const dayjs = require('dayjs');
const utc = require('dayjs/plugin/utc');
const timezone = require('dayjs/plugin/timezone');

dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.tz.setDefault('Asia/Shanghai');

const gitDatesModule = require('./build/git-dates.js');
const {
    refreshLocalArticleSnapshots,
    shouldRefreshIncompleteArticleSnapshots,
    shouldRefreshLocalArticleSnapshots
} = require('./build/article-snapshot-refresh.js');
const { loadConfig } = require('./build/config.js');
const { SOCIAL_DEFAULTS } = require('./build/social-defaults.js');
const { createEngine } = require('./build/template-engine.js');
const shared = require('./shared/shared.js');
const { copyDir, ensureCleanDir } = require('./build/fs-utils.js');
const { buildArticleFontSubset } = require('./build/fonts.js');
const { buildTailwindCss } = require('./build/tailwind.js');
const { getTailwindContentGlobs } = require('./build/tailwind-sources.js');
const { createBundler } = require('./build/bundle.js');
const { minifyDist } = require('./build/minify.js');
const postPage = require('./build/pages/post.js');
const indexPage = require('./build/pages/index.js');
const allPage = require('./build/pages/all.js');
const searchPage = require('./build/pages/search.js');
const aboutPage = require('./build/pages/about.js');
const notFoundPage = require('./build/pages/notfound.js');
const shellPage = require('./build/pages/shell.js');
const { generateSitemap, generateRobotsTxt, generateLlmsTxt, generateFeed, generateOpenSearchXml } = require('./build/pages/sitemap.js');

// ===== 路径常量 =====
const DEFAULT_POSTS_PER_PAGE = 8;
const DEFAULT_RECENT_POSTS_LIMIT = 8;
const DIRS = {
    posts: path.join(__dirname, '..', 'writing'),
    assets: path.join(__dirname, 'src', 'assets'),
    shared: path.join(__dirname, 'shared'),
    images: path.join(__dirname, 'image'),
    output: path.join(__dirname, 'dist'),
    templates: path.join(__dirname, 'src'),
    partials: path.join(__dirname, 'src', 'partials'),
    build: path.join(__dirname, 'build'),
    control: path.join(__dirname, '..', 'Control')
};

// ===== 2. 加载 git dates =====
// Production builds must use the committed snapshot generated by GitHub Actions.
// Do not fall back to file mtimes here; checkout mtimes are not article edit times.
function loadArticleSnapshots() {
    const snapshotPath = path.join(__dirname, 'git-dates.json');
    return {
        gitDates: gitDatesModule.loadSnapshot({
            snapshotPath,
            required: true,
            label: 'Git modified date',
            section: 'modified'
        }),
        postDates: gitDatesModule.loadSnapshot({
            snapshotPath,
            required: false,
            label: 'post publish date',
            section: 'published'
        }),
        postIds: gitDatesModule.loadSnapshot({
            snapshotPath,
            required: false,
            label: 'post id',
            section: 'post_ids'
        }),
        latestUpdates: gitDatesModule.loadSnapshotMap({
            snapshotPath,
            required: false,
            label: 'article latest update',
            section: 'latest_updates'
        })
    };
}

function loadPostsFromSnapshots(snapshots) {
    return postPage.loadPosts({
        postsDir: DIRS.posts,
        gitDates: snapshots.gitDates,
        postDates: snapshots.postDates,
        postIds: snapshots.postIds,
        latestUpdates: snapshots.latestUpdates,
        skipMissingGitDates: true
    });
}

function refreshLocalArticleSnapshotsIfIncomplete(snapshots) {
    const postFiles = gitDatesModule.listPostFiles(DIRS.posts);
    if (!shouldRefreshIncompleteArticleSnapshots(postFiles, snapshots)) return snapshots;

    refreshLocalArticleSnapshots({ rootDir: __dirname });
    return loadArticleSnapshots();
}

let articleSnapshots = refreshLocalArticleSnapshotsIfIncomplete(loadArticleSnapshots());

// ===== 3. 加载配置（site / social / about）=====
console.log('⚙️ Loading site configuration...');
const siteDefaults = {
    site_title: 'FreeCat Blog',
    site_name: 'FreeCat',
    footer_copyright: '© FreeCat | Curiosity is the best motivation.',
    hero_title: 'Hi, I\'m FreeCat.Building Blog & writing.',
    hero_subtitle: 'Always maintain a strong curiosity and be willing to explore a world of freedom, experiencing a life of liberty.',
    hero_avatar: '',
    posts_per_page: DEFAULT_POSTS_PER_PAGE,
    default_theme: 'system',
    site_logo_icon: '',
    site_favicon: '/image/freecat.png',
    site_url: '',
    show_recent_posts: false,
    nav_audio: '',
    nav_audio_autoplay: false
};
const siteConfig = loadConfig(DIRS.control, 'site', 'site.md', siteDefaults);
const hasConfiguredHeroAvatar = String(siteConfig.hero_avatar || '').trim() !== '';
siteConfig.hero_avatar_configured = hasConfiguredHeroAvatar;
if (!siteConfig.site_favicon) siteConfig.site_favicon = '/image/freecat.png';
if (!siteConfig.hero_avatar) siteConfig.hero_avatar = '/image/freecat.png';

const rawPostsPerPage = siteConfig.posts_per_page;
const parsedPostsPerPage = rawPostsPerPage === '' || rawPostsPerPage == null
    ? Number.NaN
    : Number(rawPostsPerPage);
const POSTS_PER_PAGE = Number.isFinite(parsedPostsPerPage) && parsedPostsPerPage >= 0
    ? Math.floor(parsedPostsPerPage)
    : DEFAULT_POSTS_PER_PAGE;
const ASSET_VERSION = process.env.CF_PAGES_COMMIT_SHA || process.env.VERCEL_GIT_COMMIT_SHA || process.env.COMMIT_SHA || String(Date.now());

console.log('📱 Loading social media configuration...');
const socialConfig = loadConfig(DIRS.control, 'social', 'social.md', SOCIAL_DEFAULTS);

console.log('🔎 Loading SEO configuration...');
const seoConfig = loadConfig(DIRS.control, 'SEO', 'SEO_搜索优化.md', {
    site_url: '',
    site_description: '',
    site_language: 'zh-CN',
    site_author: '',
    site_author_url: '',
    site_author_sameas: [],
    site_default_image: '',
    google_html_marker: '',
    bing_html_marker: '',
    allow_ai_crawlers: true,
    enable_llms_txt: true
});
if (seoConfig.site_url) siteConfig.site_url = seoConfig.site_url;
if (hasConfiguredHeroAvatar) seoConfig.site_default_image = siteConfig.hero_avatar;

console.log('👤 Loading about page configuration...');
const aboutConfig = loadConfig(DIRS.control, 'about', 'about.md', {
    about_hero_title: '',
    about_hero_subtitle: '',
    about_hero_avatar: '/image/freecat.png'
});

// ===== 4. 加载并排序文章 =====
// 提前到模板引擎之前：顶栏「查看标签」菜单要在构建期预渲染进 header。
// 因此必须先拿到全部文章，才能算出标签清单。
console.log('📝 Processing posts...');
let allPosts;
try {
    allPosts = loadPostsFromSnapshots(articleSnapshots);
} catch (err) {
    if (shouldRefreshLocalArticleSnapshots(err, gitDatesModule.MISSING_GIT_DATE_CODE)) {
        refreshLocalArticleSnapshots({ rootDir: __dirname });
        articleSnapshots = loadArticleSnapshots();
        allPosts = loadPostsFromSnapshots(articleSnapshots);
    } else {
        throw err;
    }
}

// 顶栏「查看标签」菜单：构建期一次性算好并预渲染成静态 HTML，注入每个页面的 header。
// 这样客户端首次点击只需切换一个 CSS 类即可展开（零网络、零计算、实时响应）。
// 不再首点拉取并解析整个 search-index.json。
const tagMenuItemsHtml = shared.renderTagMenuItemsHtml(
    shared.collectMenuTags(allPosts || [])
);

// ===== 5. 模板引擎 =====
// 构建期资源合并：把每页十几个 JS/CSS 引用改写为少量 bundle 引用（见 build/bundle.js）。
const bundler = createBundler({
    templatesDir: DIRS.templates,
    partialsDir: DIRS.partials,
    assetsDir: DIRS.assets,
    sharedDir: DIRS.shared
});
const engine = createEngine({
    templatesDir: DIRS.templates,
    partialsDir: DIRS.partials,
    siteConfig,
    seoConfig,
    socialConfig,
    assetVersion: ASSET_VERSION,
    tagMenuItemsHtml,
    htmlTransform: bundler.rewriteHtml
});

const tplIndex = engine.loadTemplate('template_index.html');
const tplPost = engine.loadTemplate('template_post.html');
const tplIndexAll = engine.loadTemplate('template_index_all.html');
const tplSearch = engine.loadTemplate('template_index_search.html');
const tplAbout = engine.loadTemplate('template_index_About.html');
const tplNotFound = engine.loadTemplate('template_index_404.html');
const tplShell = engine.loadTemplate('template_shell.html');

// ===== 5.5 生成最近更新文章列表 HTML =====
let recentPostsSidebarHomeWrapperHtml = '';
let recentPostsSidebarInnerHtml = '';

if (siteConfig.show_recent_posts === true) {
    const recentPosts = [...allPosts]
        .sort((a, b) => b.modifiedDate.valueOf() - a.modifiedDate.valueOf())
        .slice(0, DEFAULT_RECENT_POSTS_LIMIT);

    // 入场动画延迟：Update 紧跟简介出现，列表项仍保持轻微错峰。
    const HEADING_DELAY = 150;
    const ITEM_DELAY_STEP = 50;

    const itemsHtml = recentPosts.map((post, i) => {
        const safeTitle = engine.shared.escapeHtml(post.title);
        const safeLink = engine.shared.escapeHtml(engine.shared.encodeSitePath(post.link));
        const delay = HEADING_DELAY + (i + 1) * ITEM_DELAY_STEP;
        return `
                            <li class="py-3 animate-fade-in-up" style="animation-delay: ${delay}ms">
                                <a href="${safeLink}" class="freecat-sidebar-recent-link block text-sm text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors duration-150 line-clamp-2">
                                    ${safeTitle}
                                </a>
                            </li>`;
    }).join('\n');

    recentPostsSidebarInnerHtml = `
                        <div class="flex flex-col flex-shrink-0 mt-8">
                            <h3 class="freecat-sidebar-recent-heading text-sm tracking-wider text-slate-600 dark:text-slate-300 mb-4 animate-fade-in-up" style="animation-delay: ${HEADING_DELAY}ms">
                                Update
                            </h3>
                            <ul class="flex flex-col divide-y divide-slate-200 dark:divide-slate-700">
                                ${itemsHtml.trim()}
                            </ul>
                        </div>`;

    // 首页 / 搜索页改版后：最近更新直接渲染到左侧栏底部容器内。
    // 不再需要额外的 absolute/sticky shell 包裹，直接复用 inner 结构。
    recentPostsSidebarHomeWrapperHtml = recentPostsSidebarInnerHtml.replace(' mt-8', '').trim();

}

// ===== 1. 清理输出目录 =====
ensureCleanDir(DIRS.output, { within: __dirname, allowedName: 'dist' });
fs.mkdirSync(path.join(DIRS.output, 'posts'));

// ===== 6. 生成各页面 =====
postPage.generateAll({ posts: allPosts, template: tplPost, siteConfig, seoConfig, outputDir: DIRS.output, assetVersion: ASSET_VERSION });
indexPage.generateAll({ posts: allPosts, template: tplIndex, postsPerPage: POSTS_PER_PAGE, siteConfig, seoConfig, outputDir: DIRS.output, recentPostsSidebarHtml: recentPostsSidebarHomeWrapperHtml });
// 首页内容直出到 /（index.html）与 /home（iframe 默认内容）两个地址；
// 外壳输出到 /shell（noindex），真人浏览器在内容页上由 bootstrap 换壳启用顶栏音频无缝体验。
shellPage.generate({ template: tplShell, siteConfig, seoConfig, outputDir: DIRS.output });
allPage.generate({ posts: allPosts, template: tplIndexAll, siteConfig, seoConfig, outputDir: DIRS.output });
searchPage.generate({ posts: allPosts, template: tplSearch, siteConfig, seoConfig, outputDir: DIRS.output, recentPostsSidebarHtml: recentPostsSidebarHomeWrapperHtml });
aboutPage.generate({ template: tplAbout, siteConfig, seoConfig, aboutConfig, outputDir: DIRS.output });
notFoundPage.generateNotFoundPage({ template: tplNotFound, outputDir: DIRS.output });
generateSitemap({ posts: allPosts, siteConfig, seoConfig, outputDir: DIRS.output });
generateRobotsTxt({ siteConfig, seoConfig, outputDir: DIRS.output });
generateLlmsTxt({ posts: allPosts, siteConfig, seoConfig, outputDir: DIRS.output });
generateFeed({ posts: allPosts, siteConfig, seoConfig, outputDir: DIRS.output });
generateOpenSearchXml({ siteConfig, seoConfig, outputDir: DIRS.output });

// ===== 6.5 刷新字体子集，再搬运静态资源 =====
console.log('🔤 Refreshing generated font subsets...');
buildArticleFontSubset({ rootDir: __dirname, refresh: true });

console.log('📦 Moving assets and configs...');
if (fs.existsSync(DIRS.assets)) copyDir(DIRS.assets, path.join(DIRS.output, 'assets'), { ignore: ['posts'] });
if (fs.existsSync(DIRS.shared)) copyDir(DIRS.shared, path.join(DIRS.output, 'assets'));
if (fs.existsSync(DIRS.images)) copyDir(DIRS.images, path.join(DIRS.output, 'image'));

// ===== 6.6 生成 JS bundle（CSS bundle 需等 Tailwind 编译完成，见第 8 步之后）=====
console.log('🧩 Writing JS bundles...');
bundler.writeJsBundles(path.join(DIRS.output, 'assets'));

// ===== 7. 复制部署平台配置 (_headers / vercel.json) =====
const deployConfigs = ['_headers', 'vercel.json'];
for (const name of deployConfigs) {
    const src = path.join(DIRS.templates, name);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(DIRS.output, name));
}

// ===== 8. 编译 Tailwind（必须最后做，扫描的是已生成的 dist HTML + 拼装 HTML 字符串的 build/ JS）=====
console.log('🎨 Compiling Tailwind CSS...');
buildTailwindCss({
    contentGlobs: getTailwindContentGlobs(DIRS),
    outputPath: path.join(DIRS.output, 'assets', 'tailwind.css'),
    minify: true
}).then(async ({ size }) => {
    const sizeKb = (size / 1024).toFixed(1);
    console.log(`   tailwind.css: ${sizeKb} KB`);

    // ===== 8.5 生成 CSS bundle（依赖已编译的 tailwind.css）=====
    console.log('🧩 Writing CSS bundles...');
    const cssSizes = await bundler.writeCssBundles(path.join(DIRS.output, 'assets'), {
        minify: process.env.NO_MINIFY !== '1'
    });
    for (const [name, bytes] of Object.entries(cssSizes)) {
        console.log(`   ${name}: ${(bytes / 1024).toFixed(1)} KB`);
    }

    // ===== 9. Minify HTML / JS（必须在 Tailwind 之后，因为 Tailwind 会扫描已生成的 HTML）=====
    if (process.env.NO_MINIFY !== '1') {
        console.log('🗜️ Minifying HTML & JS...');
        await minifyDist(DIRS.output);
    }

    console.log('🚀 Build Complete: Posts & Index pages generated!');
}).catch(err => {
    console.error('❌ Build failed:', err);
    process.exit(1);
});
